### ISSUE TITLE
Username parameter is deprecated

### ISSUE THREAD

**Issue by pe3** [rOpenGov/gisfin#17]
Hello. I wanted to test gisfin for the first time but failed to install it. While trying I unfortunatelly get an error which I believe is caused by the package.
```
install.packages("devtools")
library(devtools)
install_github("gisfin", "ropengov")
```
causes:
```
* installing *source* package ‘gisfin’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (gisfin)
Warning message:
Username parameter is deprecated. Please use ropengov/gisfin 

```

**Comment by jlehtoma** [comment]
Looks like the package is installed correctly, did you get any errors while try load the package or using it? The warning can be ignored or fixed by doing
```
install_github("ropengov/gisfin")
```
We should update the tutorial on this, so thanks for reporting this!

**Comment by pe3** [comment]
It seems to work ok.

**Comment by jlehtoma** [comment]
Good, closing this issue.

**Comment by Praveen76** [comment]
Can somebody explain why did we get that warning message in first place?

**Comment by jlehtoma** [comment]
```
install_github("gisfin", "ropengov")
```
is deprecated in `devtools`. Current way of calling `install_github()` is now:

```
install_github("ropengov/gisfin")
```
