### ISSUE TITLE
get_postalcode_areas bug

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/gisfin#18]
This error occurs with the roxygen manpage and package vignette:

pnro.sp <- get_postalcode_areas()
Error in stopifnot(is.list(srl)): ring not closed

For this reason the roxygen example is now commented out with \dontrun. Remove the \dontrun after the bug has been fixed.

**Comment by statguy** [comment]
This problem is caused by old version of GDAL, please upgrade (instructions in the tutorial).
