### ISSUE TITLE
Add geoserver.hel.fi WFS api

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/gisfin#19]
Drafted GeoserverHelFi.R in branch GeoserverHelFi. Needs more data sources and documentation update.

**Comment by ouzor** [comment]
The old implementation will not be used after reboot, so there is no point in finalising it.

But the WFS api http://geoserver.hel.fi/geoserver/web/ can be added along with others.

**Comment by antagomir** [comment]
Probably outdated.
