### ISSUE TITLE
pxweb changes breaking vignette

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/gisfin#27]
pxweb R package outputs have changed and gisfin vignette examples for pxweb are now broken.

**Comment by ouzor** [comment]
I nor reran tutorial, apparently with an old version of pxweb, as it worked. Will update pxweb and fix this later.

**Comment by ouzor** [comment]
@antagomir Can you please retry this, as I have the latest version of pxweb from CRAN (0.6.3, same in Github) and the tutorial code works?

**Comment by antagomir** [comment]
Ok seems to work with the latest pxweb development version now.
