### ISSUE TITLE
Add support for Data Science Toolkit geocoding

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/gisfin#30]
Data Science Toolkit offers Google-like geocoding service that seems to have no limits for daily use: http://www.datasciencetoolkit.org/. This would be easy to add to our geocode functionality.

**Comment by h8d5lo1** [comment]
Hi @ouzor I'm having a strange problem when attempting to pip install dstk. It simply says 

```
Collecting dstk
  Could not find a version that satisfies the requirement dstk (from versions: )
No matching distribution found for dstk
```

I'm working within a virtualenv for python3. I've tried it on my other venv for python2 and i get the same error. Do you have any thoughts?

**Comment by ouzor** [comment]
Hi @Chris-Larkin! Sorry I have completely missed your question! I have no experience in using DSTK in Python, so I can not help you.

**Comment by ouzor** [comment]
Geocoding should be implemented in separate package(s), and there are already packages existing, such as [digitransit](https://github.com/rOpenGov/digitransit) and [ggmap](https://github.com/rOpenGov/digitransit) that offer geocoding.

Closing the issue.
