### ISSUE TITLE
get_postal_code_areas() causes an error in rgdal::ogrListLayers(kml.file): : Cannot open data source

### ISSUE THREAD

**Issue by philstraforelli** [rOpenGov/gisfin#32]
Hello,

I get the following error when I execute `gisfin::get_postalcode_areas()`

    Finnish postal code areas by Duukkis from http://www.palomaki.info/apps/pnro/
    Version 2.1.2015
    License: CC BY 4.0
    Downloading https://www.google.com/fusiontables/exporttable?query=select+col2+from+1m9trydaf6rdt9qBfQkU-4iRKkhNn6O1lRw7XWnXF&o=kml&g=col2&styleId=2&templateId=2
    into C:\Users\...\AppData\Local\Temp\Rtmp2FUDB7/pnro.kml

    Error in rgdal::ogrListLayers(kml.file) : Cannot open data source
    In addition: Warning messages:
    1: running command 'curl  "https://www.google.com/fusiontables/exporttable?query=select+col2+from+1m9trydaf6rdt9qBfQkU-4iRKkhNn6O1lRw7XWnXF&o=kml&g=col2&styleId=2&templateId=2"  -o "C:\Users\PSTRAF~1\AppData\Local\Temp\Rtmp2FUDB7/pnro.kml"' had status 127 
    2: In download.file(kml.url, kml.file, method = "curl") :
      download had nonzero exit status

Is this an issue I can fix on my end?

**Comment by jlehtoma** [comment]
Hi @philstraforelli ,

I could replicate the issue and it seems to be something to do using `download.file([...], method = "curl)"` in `gisfin::get_postalcode_areas()`. [URL to Google Fusiontables](https://www.google.com/fusiontables/exporttable?query=select+col2+from+1m9trydaf6rdt9qBfQkU-4iRKkhNn6O1lRw7XWnXF&o=kml&g=col2&styleId=2&templateId=2) works, but for some reason CURL trips on this. Changing the method `wget` works. The best guess is that this might have something to do with the [Dyn DNS DDoS attack](https://tech.slashdot.org/story/16/10/21/135241/several-sites-including-twitter-github-spotify-paypal-nytimes-suffering-outage----dyn-dns-under-ddos-attack-update) that's been going on today. Unless you're in a terrible rush, I'd wait until the internet recovers and give it another go.

**Comment by philstraforelli** [comment]
Thanks @jlehtoma . I can wait - I just didn't expect that attack to affect this!

**Comment by jlehtoma** [comment]
Great! Not sure if it has anything to do with this, but there has been some reports on various R packages today reporting problems with Google services.

**Comment by ouzor** [comment]
Hi @philstraforelli, I think I fixed this now, needed to update the google fusion tables url (see commit above). Please try this now and report whether it is ok!

**Comment by philstraforelli** [comment]
I got the following feedback. it seems to scrape fine from the new URL but it appears to be running into an issue with storing the kml.file:

> Downloading https://fusiontables.google.com/exporttable?query=select+col2+from+1m9trydaf6rdt9qBfQkU-4iRKkhNn6O1lRw7XWnXF&o=kml&g=col2&styleId=2&templateId=2
into C:\Users\PSTRAF~1\AppData\Local\Temp\RtmpqYsKSQ/pnro.kml

> Error in rgdal::ogrListLayers(kml.file) : Cannot open data source
> In addition: Warning messages:
> 1: running command 'curl  "https://fusiontables.google.com/exporttable?query=select+col2+from+1m9trydaf6rdt9qBfQkU-4iRKkhNn6O1lRw7XWnXF&o=kml&g=col2&styleId=2&templateId=2"  -o "C:\Users\PSTRAF~1\AppData\Local\Temp\RtmpqYsKSQ/pnro.kml"' had status 127 
> 2: In download.file(kml.url, kml.file, method = "curl") :
  download had nonzero exit status

**Comment by ouzor** [comment]
Hmm, do you have curl properly installed? With a bit of googling I found
that status 127 indicates "command not found", which would imply that curl
is not properly installed. I don't currently have a Windows machine
available so I can not reproduce the problem.
