### ISSUE TITLE
Submit the package to CRAN

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/gisfin#33]
The package is already useful, but would need more robustness before submitting to CRAN. My plan is to prioritise cleaning the current code and not adding new features before the package is in CRAN. I will likely even drop some not so necessary features for now in order to streamline the package. The WFS stuff will be removed, I have a workaround for accessing the most important WFS data source for now. When the rwfs package (https://github.com/rOpenGov/rwfs) is in CRAN, it can be used here as well.
- [ ]  Decide a place where to store code that will be removed from gisfin
- [ ]  Identify and remove features not necessary for CRAN submission
- [ ]  Implement testing
- [ ]  Rewrite code if needed

**Comment by jlehtoma** [comment]
`rwfs` is almost good to go to CRAN, I just need to sort out few test-related issues. I was [testing](https://github.com/rOpenGov/rwfs/issues/5#issuecomment-256430402) some code I found in `GeoServerHel` branch and there were some issues in how layer names are handled. That is, *if* the code in [inst/extras/test_new_geoservers.R](https://github.com/rOpenGov/gisfin/blob/GeoserverHelFi/inst/extras/test_new_geoservers.R) is still relevant.

**Comment by jlehtoma** [comment]
Feel free to drop the WFS stuff if it's not needed, of course. As for the where to put the removed code, why not clean it up (so that there is no dangling dependencies) and place in a permanent branch? Not ideal use of git, admitted.

**Comment by ouzor** [comment]
Data from the WFS sources is a very valuable addition to gisfin, so let's implement it one way or another.

**Comment by antagomir** [comment]
Some R packages use the inst directory (or inst/extras) to store code for
later use and this directory is also mentioned in R Extensions manual as a
place to store such stuff if I remember correctly. Having the materials
under the same package structure has some advantages.

**Comment by ouzor** [comment]
Hi Joona! Sorry I have missed your request to me earlier! The WFS stuff is
very relevant, I use it at work also :) I'll the rwfs package out and let's
discuss more later.
