### ISSUE TITLE
Consider using the new sf (simple features) pipeline package 

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/gisfin#35]
See examples here: http://walkerke.github.io/2016/12/spatial-pipelines/
And the package here: https://cran.r-project.org/web/packages/sf/index.html

**Comment by jlehtoma** [comment]
I'll have a stab at this in new branch `sf-based-mml`. I'll try it out with the MML data (`get_mml()` and see how it goes.

**Comment by antagomir** [comment]
Will be considered during rewrite.
