### ISSUE TITLE
Fix MML dataset locations

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/gisfin#36]
`list_mml_datasets()` fails, as http://data.okf.fi/ropengov/avoindata/mml/rdata/ is not available. Could be changed to point to https://github.com/avoindata/mml/tree/master/rdata.

See also https://github.com/rOpenGov/sorvi/issues/11.

**Comment by ouzor** [comment]
See also https://github.com/rOpenGov/eurostat/issues/69

**Comment by jlehtoma** [comment]
While working on `sf-based-mml` (#35), I soon bumped into this because no data is currently available. Getting the data from Github is straight forward, but all the data and scripts in https://github.com/avoindata/mml should be updated too. This is a deeeep rabbit hole.

**Comment by jlehtoma** [comment]
I opened an issue https://github.com/avoindata/mml/issues/1
