### ISSUE TITLE
get_geocode not working

### ISSUE THREAD

**Issue by andgan** [rOpenGov/gisfin#42]
I tried:
```
gc3 <- get_geocode("Mannerheimintie 100, Helsinki", service="google")
Error in get_geocode("Mannerheimintie 100, Helsinki", service = "google") : 
  No geocode found
```

**Comment by antagomir** [comment]
Thanks! We are planning a major rewrite of the package, so this has to wait a bit. If you can provide a fix through PR meanwhile that would be welcome and can be incorporated.

**Comment by muuankarski** [comment]
Dear, @andgan, services behind the geocoding functions do not work anymore. To geocode locations in Finland, please have a look at digitransit-package: https://github.com/rOpenGov/digitransit. In case you need to geocode foreign locations OR you just want to use Google, have a look at geocode function in ggmap-package: https://github.com/dkahle/ggmap
