### ISSUE TITLE
404 error for ZIPs (get_helsinki_aluejakokartat)

### ISSUE THREAD

**Issue by kuprinaga** [rOpenGov/gisfin#49]
Hi! I've just installed the package and I'm having trouble downloading Helsinki maps.

`kunta <- get_helsinki_aluejakokartat(map.specifier="kunta")`

results in an error:

> Helsinki region district boundaries (Paakaupunkiseudun aluejakokartat) (C) HKK 2011
> Licence: 'http://ptp.hel.fi/avoindata/aineistot/Kartta_avoindata_kayttoehdot_v02_3_2011.pdf'
> Dowloading http://ptp.hel.fi/avoindata/aineistot/PKS_Kartta_Rajat_KML2011.zip
> into C:\Users\anast\AppData\Local\Temp\RtmpOaKML1/PKS_Kartta_Rajat_KML2011.zip
> 
> trying URL 'http://ptp.hel.fi/avoindata/aineistot/PKS_Kartta_Rajat_KML2011.zip'
> Error in utils::download.file(remote.zip, destfile = local.zip, quiet = !verbose) : 
>   cannot open URL 'http://ptp.hel.fi/avoindata/aineistot/PKS_Kartta_Rajat_KML2011.zip'
> In addition: Warning message:
> In utils::download.file(remote.zip, destfile = local.zip, quiet = !verbose) :
>   cannot open URL 'http://ptp.hel.fi/avoindata/aineistot/PKS_Kartta_Rajat_KML2011.zip': HTTP status was '404 Not Found'

and indeed, if I visit [the zip link](http://ptp.hel.fi/avoindata/aineistot/PKS_Kartta_Rajat_KML2011.zip), I get a 404 not found error.

**Comment by antagomir** [comment]
Hi - it seems that the City of Helsinki has changed the URLs. You can try to locate the new files at https://www.hel.fi/helsinki/fi/kartat-ja-liikenne/kartat-ja-paikkatieto/Paikkatiedot+ja+-aineistot/avoimet+paikkatiedot/ - what comes to the gisfin R package, we are going through a major rewrite and it may take for a while to get this fixed.

**Comment by kuprinaga** [comment]
Thanks for the response! :)
