### ISSUE TITLE
Fix MML data

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/gisfin#8]
Problems: 
1. list_mml_datasets() does not give any results for folder 2012/, as it contains subdirectories
2. Scandinavian characters wrong for Yleiskartta-4500 - Maakunta.FI (fixed with iconv from=UTF-8 to=ISO-8859-1

**Comment by antagomir** [comment]
Moreover, now as the OKF server is done we get error from 
datasets <- list_mml_datasets()
